import React, { useState, useEffect, useRef } from 'react';
import { 
  FileText, 
  Printer, 
  CheckCircle2, 
  ShieldAlert, 
  TrendingUp, 
  Sparkles, 
  AlertCircle, 
  Trash2, 
  Download, 
  ShieldCheck, 
  Save, 
  FileCheck, 
  Settings, 
  Clock, 
  ToggleLeft, 
  ToggleRight, 
  AlertTriangle 
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { jsPDF } from 'jspdf';
import { LinuxServer, MemoryEvent } from '../types';

interface ReportsGeneratorProps {
  servers: LinuxServer[];
  events: MemoryEvent[];
}

interface SavedReportSnapshot {
  id: string;
  timestamp: string;
  trigger: 'automatic' | 'manual';
  triggerIncidentMessage?: string;
  serversCount: number;
  incidentsCount: number;
  serversSnapshot: LinuxServer[];
  eventsSnapshot: MemoryEvent[];
}

// Helper to generate professional PDF report using jsPDF
const generatePDF = (servers: LinuxServer[], events: MemoryEvent[], isAutoGenerated = false) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  // Color Palette
  const primaryColor = [15, 23, 42]; // Slate 900
  const accentColor = [6, 182, 212];  // Cyan 500
  const secondaryColor = [71, 85, 105]; // Slate 600
  const lightBg = [248, 250, 252]; // Slate 50
  const textDark = [15, 23, 42];
  const textMuted = [100, 116, 139];

  // Draw Title / Header Banner
  doc.setFillColor(15, 23, 42); // Slate 900 header
  doc.rect(0, 0, 210, 38, 'F');

  // AIME Logo block in header
  doc.setTextColor(6, 182, 212); // Cyan text
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('AIME INFRASTRUCTURE CORE', 15, 16);

  doc.setTextColor(255, 255, 255);
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.text('SRE COMPLIANCE & INCIDENT SNAPSHOT', 15, 22);

  // Metadata block (right aligned)
  doc.setFontSize(8);
  doc.setFont('Courier', 'normal');
  const reportId = `AIM-SRE-${Math.floor(100000 + Math.random() * 900000)}`;
  doc.text(`REPORT ID: ${reportId}`, 140, 12);
  const nowStr = new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC';
  doc.text(`GENERATED: ${nowStr}`, 140, 17);
  doc.setTextColor(6, 182, 212);
  doc.setFont('Helvetica', 'bold');
  doc.text('CLASSIFICATION: CONFIDENTIAL', 140, 22);
  if (isAutoGenerated) {
    doc.setTextColor(239, 68, 68);
    doc.text('TRIGGER: AUTOMATIC INCIDENT AUTO-SAVE', 140, 27);
  } else {
    doc.text('TRIGGER: OPERATOR MANUAL EXPORT', 140, 27);
  }

  let y = 50;

  // 1. Executive Summary Section
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(6, 182, 212);
  doc.text('1. EXECUTIVE SUMMARY', 15, y);
  
  // Underline or line
  doc.setDrawColor(226, 232, 240); // Slate 200
  doc.setLineWidth(0.5);
  doc.line(15, y + 2, 195, y + 2);
  y += 8;

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(15, 23, 42);
  
  const summaryText = `This document registers the official status and structural integrity of connected server hosts, software microservices, container networks, and chronological operational history logs compiled by the AIME Infrastructure SRE Core. This report was compiled to serve as an immutable compliance record.`;
  const splitSummary = doc.splitTextToSize(summaryText, 180);
  doc.text(splitSummary, 15, y);
  y += splitSummary.length * 5 + 4;

  // 2. Performance Metrics
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(6, 182, 212);
  doc.text('2. HEALTH & PERFORMANCE METRICS', 15, y);
  doc.line(15, y + 2, 195, y + 2);
  y += 8;

  // Grid background
  doc.setFillColor(248, 250, 252); // Slate 50
  doc.setDrawColor(226, 232, 240);
  doc.rect(15, y, 180, 24, 'F');
  doc.rect(15, y, 180, 24, 'S');

  // Compute statistics
  const totalServers = servers.length > 0 ? servers.length : 1;
  const healthyCount = servers.filter(s => s.status === 'healthy').length;
  const rawAvgCpu = Math.round(servers.reduce((sum, s) => sum + (Number(s.cpu) || 0), 0) / totalServers);
  const avgCpu = isNaN(rawAvgCpu) ? 0 : rawAvgCpu;
  const rawAvgRam = Math.round(servers.reduce((sum, s) => sum + (Number(s.ram) || 0), 0) / totalServers);
  const avgRam = isNaN(rawAvgRam) ? 0 : rawAvgRam;
  const rawAvgDisk = Math.round(servers.reduce((sum, s) => sum + (Number(s.disk) || 0), 0) / totalServers);
  const avgDisk = isNaN(rawAvgDisk) ? 0 : rawAvgDisk;

  // Draw 4 columns inside the rect
  const colWidth = 180 / 4;
  for (let i = 1; i < 4; i++) {
    doc.line(15 + i * colWidth, y, 15 + i * colWidth, y + 24);
  }

  // Col 1 Content
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.setFont('Helvetica', 'bold');
  doc.text('CONNECTED HOSTS', 15 + 2, y + 6);
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text(`${totalServers} Servers`, 15 + 2, y + 14);
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text(`(${healthyCount} Healthy)`, 15 + 2, y + 20);

  // Col 2 Content
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text('AVG CPU LOAD', 15 + colWidth + 2, y + 6);
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text(`${avgCpu}%`, 15 + colWidth + 2, y + 14);
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text('LOAD STEADY', 15 + colWidth + 2, y + 20);

  // Col 3 Content
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text('AVG MEMORY USED', 15 + 2 * colWidth + 2, y + 6);
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text(`${avgRam}%`, 15 + 2 * colWidth + 2, y + 14);
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text('OPTIMIZED', 15 + 2 * colWidth + 2, y + 20);

  // Col 4 Content
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text('AVG DISK SPACE', 15 + 3 * colWidth + 2, y + 6);
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text(`${avgDisk}%`, 15 + 3 * colWidth + 2, y + 14);
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text('92% MAX LIMIT', 15 + 3 * colWidth + 2, y + 20);

  y += 32;

  // 3. SRE Incident Logs
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(6, 182, 212);
  doc.text('3. HIGH-PRIORITY SRE INCIDENT MEMORY LOGS', 15, y);
  doc.line(15, y + 2, 195, y + 2);
  y += 8;

  const incidents = events.filter(e => e.type === 'incident').slice(0, 4); // Show top 4 incidents to prevent overflow
  if (incidents.length === 0) {
    doc.setFont('Helvetica', 'italic');
    doc.setFontSize(9.5);
    doc.setTextColor(100, 116, 139);
    doc.text('No unresolved incidents reported in this observation cycle.', 15, y);
    y += 10;
  } else {
    incidents.forEach((incident) => {
      // Draw small incident block
      doc.setFillColor(248, 250, 252);
      doc.rect(15, y, 180, 18, 'F');
      doc.rect(15, y, 180, 18, 'S');

      // Left bar colored (red for critical, yellow for warning)
      if (incident.severity === 'critical') {
        doc.setFillColor(239, 68, 68); // Red
      } else {
        doc.setFillColor(245, 158, 11); // Amber
      }
      doc.rect(15, y, 2.5, 18, 'F');

      doc.setFont('Courier-Bold', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(15, 23, 42);
      doc.text(`NODE: ${incident.serverName}`, 20, y + 5);

      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(100, 116, 139);
      doc.text(new Date(incident.timestamp).toUTCString(), 125, y + 5);

      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(15, 23, 42);
      doc.text(incident.message, 20, y + 10);

      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      const detailSlice = incident.details && incident.details.length > 105 
        ? incident.details.slice(0, 105) + '...' 
        : incident.details || 'No additional details logged.';
      doc.text(detailSlice, 20, y + 14);

      y += 22;
    });
  }

  // 4. Actionable Mitigations / Recommendations
  if (y > 220) {
    doc.addPage();
    y = 25;
  }

  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(6, 182, 212);
  doc.text('4. ACTIONABLE SRE AI RECOMMENDATIONS', 15, y);
  doc.line(15, y + 2, 195, y + 2);
  y += 8;

  doc.setFillColor(236, 254, 255); // Cyan 50 light bg
  doc.setDrawColor(6, 182, 212);
  doc.rect(15, y, 180, 32, 'F');
  doc.rect(15, y, 180, 32, 'S');

  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(6, 182, 212);
  doc.text('RECOMMENDED MITIGATIONS (AIME AI ENGINE):', 20, y + 6);

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  doc.text('• Nginx Socket Pool Limits: Adjust worker rlimit caps to bypass gateway timeouts.', 20, y + 12);
  doc.text('• Redis OOM Constraints: Apply eviction policies to prevent OS kernel kills.', 20, y + 18);
  doc.text('• Transaction Log Rotation: Purge pg_wal archive sectors periodically.', 20, y + 24);

  y += 42;

  // Authorization Signatures
  if (y > 250) {
    doc.addPage();
    y = 25;
  }

  doc.setDrawColor(226, 232, 240);
  doc.line(15, y, 195, y);
  y += 8;

  doc.setFont('Courier', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('AUTHORIZED BY: AIME AI SRE CORE DECISION UNIT', 15, y);
  doc.text('SIGNATURE SECURE PROTOCOL // VERIFIED', 115, y);

  return { doc, reportId };
};

export default function ReportsGenerator({ servers, events }: ReportsGeneratorProps) {
  const printAreaRef = useRef<HTMLDivElement>(null);

  // Load automation settings and saved snapshots from browser storage
  const [autoReportEnabled, setAutoReportEnabled] = useState<boolean>(() => {
    const saved = localStorage.getItem('aime_auto_report_enabled');
    return saved === 'true'; // Default is false
  });

  const [savedReports, setSavedReports] = useState<SavedReportSnapshot[]>(() => {
    const saved = localStorage.getItem('aime_saved_reports');
    return saved ? JSON.parse(saved) : [];
  });

  const [processedEventIds, setProcessedEventIds] = useState<string[]>(() => {
    const saved = localStorage.getItem('aime_processed_event_ids');
    return saved ? JSON.parse(saved) : [];
  });

  // Pulse effect trigger on new snapshot
  const [pulseNewId, setPulseNewId] = useState<string | null>(null);

  // Sync auto-report settings
  useEffect(() => {
    localStorage.setItem('aime_auto_report_enabled', String(autoReportEnabled));
  }, [autoReportEnabled]);

  // Sync processed events and saved snapshots
  useEffect(() => {
    localStorage.setItem('aime_processed_event_ids', JSON.stringify(processedEventIds));
  }, [processedEventIds]);

  useEffect(() => {
    localStorage.setItem('aime_saved_reports', JSON.stringify(savedReports));
  }, [savedReports]);

  // Compute metrics for active view
  const totalServers = servers.length > 0 ? servers.length : 1;
  const healthyCount = servers.filter(s => s.status === 'healthy').length;
  const criticalCount = servers.filter(s => s.status === 'critical').length;
  const warningCount = servers.filter(s => s.status === 'warning').length;

  const totalIncidentsCount = events.filter(e => e.type === 'incident').length;
  const resolvedIncidentsCount = events.filter(e => e.type === 'fix').length;

  const rawAvgCpu2 = Math.round(servers.reduce((sum, s) => sum + (Number(s.cpu) || 0), 0) / totalServers);
  const avgCpu = isNaN(rawAvgCpu2) ? 0 : rawAvgCpu2;
  const rawAvgRam2 = Math.round(servers.reduce((sum, s) => sum + (Number(s.ram) || 0), 0) / totalServers);
  const avgRam = isNaN(rawAvgRam2) ? 0 : rawAvgRam2;
  const rawAvgDisk2 = Math.round(servers.reduce((sum, s) => sum + (Number(s.disk) || 0), 0) / totalServers);
  const avgDisk = isNaN(rawAvgDisk2) ? 0 : rawAvgDisk2;

  // Continuous background synchronization check for critical incident occurrences
  useEffect(() => {
    if (!autoReportEnabled) return;

    // Filter events for 'critical' severity incidents
    const criticalIncidents = events.filter(
      e => e.type === 'incident' && e.severity === 'critical'
    );

    // Filter those we haven't processed yet
    const newCriticals = criticalIncidents.filter(
      e => !processedEventIds.includes(e.id)
    );

    if (newCriticals.length > 0) {
      const updatedReports = [...savedReports];
      const updatedProcessed = [...processedEventIds];
      let newestId: string | null = null;

      newCriticals.forEach((incident) => {
        const reportId = `AIM-SRE-${Math.floor(100000 + Math.random() * 900000)}`;
        newestId = reportId;

        // Take snapshot of current state
        const newReport: SavedReportSnapshot = {
          id: reportId,
          timestamp: new Date().toISOString(),
          trigger: 'automatic',
          triggerIncidentMessage: `${incident.serverName}: ${incident.message}`,
          serversCount: servers.length,
          incidentsCount: events.filter(e => e.type === 'incident').length,
          serversSnapshot: JSON.parse(JSON.stringify(servers)),
          eventsSnapshot: JSON.parse(JSON.stringify(events)),
        };

        updatedReports.unshift(newReport);
        updatedProcessed.push(incident.id);
      });

      setSavedReports(updatedReports);
      setProcessedEventIds(updatedProcessed);

      if (newestId) {
        setPulseNewId(newestId);
        setTimeout(() => setPulseNewId(null), 8000);
      }
    }
  }, [events, servers, autoReportEnabled, processedEventIds, savedReports]);

  // Native Print fallback
  const handlePrint = () => {
    window.print();
  };

  // Instant branded PDF Download
  const handleDownloadDirectPDF = () => {
    const { doc, reportId } = generatePDF(servers, events, false);
    doc.save(`${reportId}.pdf`);
  };

  // Manual snapshot capture
  const handleSaveManualSnapshot = () => {
    const reportId = `AIM-SRE-${Math.floor(100000 + Math.random() * 900000)}`;
    const newReport: SavedReportSnapshot = {
      id: reportId,
      timestamp: new Date().toISOString(),
      trigger: 'manual',
      serversCount: servers.length,
      incidentsCount: events.filter(e => e.type === 'incident').length,
      serversSnapshot: JSON.parse(JSON.stringify(servers)),
      eventsSnapshot: JSON.parse(JSON.stringify(events)),
    };

    const updatedReports = [newReport, ...savedReports];
    setSavedReports(updatedReports);
    setPulseNewId(reportId);
    setTimeout(() => setPulseNewId(null), 5000);

    // Also download it instantly for immediate confirmation
    triggerDownload(newReport);
  };

  // Re-download from snapshot
  const triggerDownload = (report: SavedReportSnapshot) => {
    const { doc } = generatePDF(
      report.serversSnapshot, 
      report.eventsSnapshot, 
      report.trigger === 'automatic'
    );
    doc.save(`${report.id}.pdf`);
  };

  // Delete a snapshot
  const handleDeleteSnapshot = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const updated = savedReports.filter(r => r.id !== id);
    setSavedReports(updated);
  };

  // Clear all saved snapshots
  const handleClearAllSnapshots = () => {
    if (window.confirm('Are you sure you want to delete all saved compliance snapshots from local storage?')) {
      setSavedReports([]);
      setProcessedEventIds([]);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header controls (hidden on print) */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 print:hidden">
        <div>
          <h1 className="text-xl font-sans font-bold text-white tracking-tight flex items-center gap-2">
            <FileText className="w-5 h-5 text-cyan-400" />
            SRE Report Generator & Exporter
          </h1>
          <p className="text-xs text-slate-400 font-mono">COMPILE INCIDENT SUMMARIES & AUDIT-READY COMPLIANCE SNAPSHOTS</p>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <button
            onClick={handleSaveManualSnapshot}
            className="px-4 py-2.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-xs transition-all flex items-center gap-2 cursor-pointer shadow-lg shadow-indigo-500/15"
          >
            <Save className="w-4 h-4" /> Save Snapshot
          </button>
          <button
            onClick={handleDownloadDirectPDF}
            className="px-4 py-2.5 rounded-lg bg-cyan-500 text-slate-950 font-bold text-xs hover:bg-cyan-400 transition-all flex items-center gap-2 cursor-pointer shadow-lg shadow-cyan-500/15"
          >
            <Download className="w-4 h-4" /> Branded PDF Report
          </button>
          <button
            onClick={handlePrint}
            className="px-4 py-2.5 rounded-lg bg-slate-800 border border-slate-700 hover:bg-slate-700 text-slate-200 font-semibold text-xs transition-all flex items-center gap-2 cursor-pointer"
          >
            <Printer className="w-4 h-4" /> Print Document
          </button>
        </div>
      </div>

      {/* AUTOMATION ENGINE PANEL (hidden on print) */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 print:hidden">
        {/* Toggle Automation Card */}
        <div className="p-5 rounded-xl border border-slate-800/80 bg-slate-900/40 backdrop-blur-sm space-y-4">
          <div className="flex items-center gap-2 text-indigo-400">
            <Settings className="w-4 h-4" />
            <h2 className="text-xs font-mono font-bold uppercase tracking-wider">Compliance Automation Engine</h2>
          </div>
          <div className="space-y-3">
            <p className="text-[11px] text-slate-400 font-sans leading-relaxed">
              Enable active SRE core background triggers to archive a permanent PDF compliance report record instantly when severe, critical infrastructure state changes occur.
            </p>
            <div className="flex items-center justify-between p-3 rounded-lg bg-slate-950 border border-slate-800/80">
              <span className="text-xs font-semibold text-slate-300">Auto PDF Save on Critical Incident</span>
              <button
                onClick={() => setAutoReportEnabled(!autoReportEnabled)}
                className="text-slate-400 hover:text-white transition-colors focus:outline-none cursor-pointer"
              >
                {autoReportEnabled ? (
                  <ToggleRight className="w-10 h-10 text-cyan-400 transition-all" />
                ) : (
                  <ToggleLeft className="w-10 h-10 text-slate-600 transition-all" />
                )}
              </button>
            </div>
            {autoReportEnabled ? (
              <div className="flex items-center gap-2 text-[10px] font-mono text-cyan-400 bg-cyan-950/20 border border-cyan-500/10 rounded px-2.5 py-1.5 animate-pulse">
                <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 block shrink-0" />
                ACTIVE AUTO-MONITORING PROTOCOL ONLINE
              </div>
            ) : (
              <div className="flex items-center gap-2 text-[10px] font-mono text-slate-500 bg-slate-950 border border-slate-900 rounded px-2.5 py-1.5">
                <span className="w-1.5 h-1.5 rounded-full bg-slate-600 block shrink-0" />
                AUTO-MONITORING BYPASSED
              </div>
            )}
          </div>
        </div>

        {/* Saved Snapshots List Card */}
        <div className="lg:col-span-2 p-5 rounded-xl border border-slate-800/80 bg-slate-900/40 backdrop-blur-sm flex flex-col h-full min-h-[220px]">
          <div className="flex items-center justify-between pb-3 border-b border-slate-800/60 mb-3">
            <div className="flex items-center gap-2 text-indigo-400">
              <Clock className="w-4 h-4" />
              <h2 className="text-xs font-mono font-bold uppercase tracking-wider">Saved Compliance Snapshot History ({savedReports.length})</h2>
            </div>
            {savedReports.length > 0 && (
              <button
                onClick={handleClearAllSnapshots}
                className="text-[10px] font-mono font-bold text-red-400 hover:text-red-300 transition-colors uppercase cursor-pointer"
              >
                Clear History
              </button>
            )}
          </div>

          <div className="flex-1 overflow-y-auto max-h-36 pr-1 space-y-2">
            <AnimatePresence initial={false}>
              {savedReports.length === 0 ? (
                <div className="h-full flex flex-col items-center justify-center text-center py-6">
                  <FileCheck className="w-8 h-8 text-slate-700 mb-2" />
                  <p className="text-xs text-slate-500">No automated or manual compliance reports saved yet.</p>
                  <p className="text-[10px] text-slate-600 max-w-xs mt-1">Enable auto-pdf toggle above or click "Save Snapshot" to compile an offline compliance state record.</p>
                </div>
              ) : (
                savedReports.map((report) => {
                  const isNew = report.id === pulseNewId;
                  return (
                    <motion.div
                      key={report.id}
                      initial={{ opacity: 0, height: 0, y: -10 }}
                      animate={{ opacity: 1, height: 'auto', y: 0 }}
                      exit={{ opacity: 0, height: 0 }}
                      transition={{ duration: 0.2 }}
                      className={`p-3 rounded-lg border flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs bg-slate-950 transition-all ${
                        isNew 
                          ? 'border-cyan-500/55 shadow-md shadow-cyan-500/5' 
                          : 'border-slate-800/70 hover:border-slate-700'
                      }`}
                    >
                      <div className="space-y-1">
                        <div className="flex items-center gap-2">
                          <span className="font-mono font-bold text-slate-200">{report.id}</span>
                          {report.trigger === 'automatic' ? (
                            <span className="px-1.5 py-0.5 rounded text-[8px] font-mono font-bold uppercase tracking-widest bg-red-500/10 text-red-400 border border-red-500/20 flex items-center gap-1">
                              <AlertTriangle className="w-2 h-2" /> Auto-Saved
                            </span>
                          ) : (
                            <span className="px-1.5 py-0.5 rounded text-[8px] font-mono font-bold uppercase tracking-widest bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
                              Manual
                            </span>
                          )}
                        </div>
                        <p className="text-[10px] text-slate-400 font-mono">
                          {new Date(report.timestamp).toLocaleString()} • {report.serversCount} Servers • {report.incidentsCount} Incidents
                        </p>
                        {report.triggerIncidentMessage && (
                          <p className="text-[10px] text-slate-500 font-mono italic truncate max-w-sm">
                            Reason: {report.triggerIncidentMessage}
                          </p>
                        )}
                      </div>
                      <div className="flex items-center gap-2 self-end sm:self-auto">
                        <button
                          onClick={() => triggerDownload(report)}
                          className="px-2.5 py-1.5 rounded bg-slate-900 border border-slate-800 text-slate-300 hover:text-white hover:border-slate-700 hover:bg-slate-800 transition-all flex items-center gap-1 font-semibold text-[11px] cursor-pointer"
                          title="Download report as PDF file"
                        >
                          <Download className="w-3.5 h-3.5" /> PDF
                        </button>
                        <button
                          onClick={(e) => handleDeleteSnapshot(report.id, e)}
                          className="p-1.5 rounded bg-slate-900/50 border border-slate-800/80 text-slate-500 hover:text-red-400 hover:border-red-500/20 hover:bg-red-500/5 transition-all cursor-pointer"
                          title="Delete snapshot from local storage"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    </motion.div>
                  );
                })
              )}
            </AnimatePresence>
          </div>
        </div>
      </div>

      {/* SRE Compliance Report Document */}
      <div 
        ref={printAreaRef}
        className="rounded-xl border border-slate-900 bg-slate-950 p-8 sm:p-12 text-left max-w-4xl mx-auto space-y-8 shadow-2xl print:bg-white print:text-slate-950 print:border-none print:shadow-none print:p-0"
      >
        {/* Report Document Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6 pb-6 border-b border-slate-900 print:border-slate-300">
          <div className="space-y-1.5">
            <div className="flex items-center gap-2">
              <FileText className="w-6 h-6 text-cyan-400 print:text-cyan-600" />
              <span className="font-sans font-extrabold text-lg text-white print:text-slate-950">AI INFRASTRUCTURE MEMORY</span>
            </div>
            <p className="text-xs text-slate-400 font-mono print:text-slate-500">SRE SYSTEM COMPLIANCE & INCIDENT REPORT</p>
          </div>
          <div className="text-right font-mono text-xs text-slate-500">
            <p>REPORT ID: AIM-SRE-{Date.now().toString().slice(-6)}</p>
            <p>GENERATED: {new Date().toISOString().replace('T', ' ').slice(0, 16)} UTC</p>
            <p className="text-cyan-400 print:text-cyan-600 font-bold">CLASSIFICATION: CONFIDENTIAL</p>
          </div>
        </div>

        {/* Section 1: Executive Summary */}
        <div className="space-y-3">
          <h3 className="text-xs font-mono font-bold text-cyan-400 print:text-cyan-600 uppercase tracking-widest flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4" /> 1. Executive Summary
          </h3>
          <p className="text-sm text-slate-300 print:text-slate-800 leading-relaxed font-sans">
            This document registers the official status and structural integrity of connected server hosts, software microservices, container networks, and chronological operational history logs compiled by the <strong>AIME Infrastructure SRE Core</strong>. During the current observation window, the core has successfully archived all critical alerts and admin shell command sessions.
          </p>
        </div>

        {/* Section 2: Farm Metrics Matrix */}
        <div className="space-y-4">
          <h3 className="text-xs font-mono font-bold text-cyan-400 print:text-cyan-600 uppercase tracking-widest flex items-center gap-2">
            <TrendingUp className="w-4 h-4" /> 2. Infrastructure Health & Performance Metrics
          </h3>
          
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <div className="p-4 rounded-lg bg-slate-900/40 border border-slate-900 text-center print:border-slate-300 print:bg-slate-50">
              <span className="block text-[10px] font-mono text-slate-500 uppercase">Server Hosts</span>
              <span className="text-2xl font-bold text-white print:text-slate-950">{totalServers}</span>
              <span className="block text-[9px] font-mono text-slate-500 mt-0.5">({healthyCount} Healthy)</span>
            </div>
            <div className="p-4 rounded-lg bg-slate-900/40 border border-slate-900 text-center print:border-slate-300 print:bg-slate-50">
              <span className="block text-[10px] font-mono text-slate-500 uppercase">Avg CPU Utilization</span>
              <span className="text-2xl font-bold text-white print:text-slate-950">{avgCpu}%</span>
              <span className="block text-[9px] font-mono text-slate-500 mt-0.5">LOAD STEADY</span>
            </div>
            <div className="p-4 rounded-lg bg-slate-900/40 border border-slate-900 text-center print:border-slate-300 print:bg-slate-50">
              <span className="block text-[10px] font-mono text-slate-500 uppercase">Avg Memory Used</span>
              <span className="text-2xl font-bold text-white print:text-slate-950">{avgRam}%</span>
              <span className="block text-[9px] font-mono text-slate-500 mt-0.5">CAPACITY OPTIMIZED</span>
            </div>
            <div className="p-4 rounded-lg bg-slate-900/40 border border-slate-900 text-center print:border-slate-300 print:bg-slate-50">
              <span className="block text-[10px] font-mono text-slate-500 uppercase">Avg Disk Space</span>
              <span className="text-2xl font-bold text-white print:text-slate-950">{avgDisk}%</span>
              <span className="block text-[9px] font-mono text-slate-500 mt-0.5">92% MAXIMUM LIMIT</span>
            </div>
          </div>
        </div>

        {/* Section 3: Incident Log Summary */}
        <div className="space-y-4">
          <h3 className="text-xs font-mono font-bold text-cyan-400 print:text-cyan-600 uppercase tracking-widest flex items-center gap-2">
            <ShieldAlert className="w-4 h-4" /> 3. High-Priority SRE Incident Memory Logs
          </h3>

          <div className="space-y-3.5">
            {events.filter(e => e.type === 'incident').length === 0 ? (
              <div className="p-4 rounded-lg border border-slate-900 bg-slate-900/10 text-center font-mono text-xs text-slate-500">
                No system incidents reported in the current window.
              </div>
            ) : (
              events.filter(e => e.type === 'incident').slice(0, 5).map((incident) => {
                let tag = 'text-red-500 bg-red-500/10 border-red-500/20';
                if (incident.severity === 'warning') tag = 'text-yellow-500 bg-yellow-500/10 border-yellow-500/20';

                return (
                  <div 
                    key={incident.id} 
                    className="p-4 rounded-lg border border-slate-900 bg-slate-900/20 print:border-slate-300 print:bg-slate-50 space-y-1.5"
                  >
                    <div className="flex items-center justify-between text-xs font-mono">
                      <span className="font-bold text-cyan-400 print:text-cyan-600">NODE: {incident.serverName}</span>
                      <span className="text-slate-500">{new Date(incident.timestamp).toUTCString()}</span>
                    </div>
                    <h4 className="text-sm font-bold text-white print:text-slate-950">{incident.message}</h4>
                    <p className="text-xs text-slate-400 print:text-slate-600 leading-relaxed">{incident.details}</p>
                  </div>
                );
              })
            )}
          </div>
        </div>

        {/* Section 4: AI Recommendations */}
        <div className="space-y-4 pt-2">
          <h3 className="text-xs font-mono font-bold text-cyan-400 print:text-cyan-600 uppercase tracking-widest flex items-center gap-2">
            <Sparkles className="w-4 h-4" /> 4. Actionable AIME AI Recommendations
          </h3>

          <div className="p-5 rounded-lg border border-cyan-500/15 bg-cyan-950/10 print:border-slate-300 print:bg-slate-50 text-xs sm:text-sm text-slate-300 print:text-slate-800 space-y-3 font-sans">
            <p className="font-bold flex items-center gap-1.5 text-cyan-400 print:text-cyan-700">
              <AlertCircle className="w-4 h-4" /> Recommended Mitigations:
            </p>
            <ul className="list-disc pl-5 space-y-2 leading-relaxed">
              <li>
                <strong>Nginx Socket Pool limits</strong>: Configure <code>worker_rlimit_nofile 8192</code> alongside <code>worker_connections 4096</code> on srv-nginx-prod node to avoid HTTP 504 connection gateway drops during future traffic peaks.
              </li>
              <li>
                <strong>Redis OOM constraints</strong>: Enforce memory caps (<code>--memory 1g</code>) and an evictions policy (<code>maxmemory-policy allkeys-lru</code>) in docker-compose configs to prevent system kernel level terminations.
              </li>
              <li>
                <strong>Persistent WAL replication limit</strong>: Automatically rotate pg_wal transaction logs on srv-db-primary to keep disk thresholds comfortably below 85% utilization limits.
              </li>
            </ul>
          </div>
        </div>

        {/* Document Footer signatures */}
        <div className="pt-8 border-t border-slate-900 print:border-slate-300 flex flex-col sm:flex-row justify-between items-center text-xs font-mono text-slate-600 gap-4">
          <p>AUTHORIZED BY: AIME AI SRE CORE DECISION UNIT</p>
          <p className="border-t border-dashed border-slate-800 pt-1 sm:border-0 sm:pt-0">SIGNATURE: _______________________</p>
        </div>
      </div>
    </div>
  );
}
