export interface LinuxServer {
  id: string;
  name: string;
  ip: string;
  os: string;
  status: 'healthy' | 'warning' | 'critical';
  uptime: string;
  cpu: number;
  ram: number;
  disk: number;
  provider: string;
  region: string;
  sshPort: number;
  sshUser: string;
}

export type MemoryEventType = 'incident' | 'error' | 'command' | 'config' | 'deployment' | 'fix';

export interface MemoryEvent {
  id: string;
  timestamp: string; // ISO String
  serverId: string;
  serverName: string;
  type: MemoryEventType;
  message: string;
  user: string;
  details?: string;
  category?: string; // e.g. nginx, docker, kernel, mysql
  commandExitCode?: number;
  severity?: 'healthy' | 'warning' | 'critical';
  
  // Change Attribution & Audit Trail Fields
  team?: string;
  changeReason?: string;
  commitId?: string;
  terraformApplyId?: string;
  gitBranch?: string;
  pullRequest?: string;
  jiraTicket?: string;
  environment?: 'Dev' | 'QA' | 'Production';
  editableNote?: string;
  relatedResources?: string; // e.g. "sg-03ea21, i-09f12a3bc"
  status?: string; // e.g. "active", "deleted", "drifted", "failed", "resolved"
  
  // AI Pattern Analysis & Risk Scoring
  riskScore?: number; // 0 to 100 risk score generated by Gemini API
  aiFlagged?: boolean;
  aiPatternCategory?: string;
  aiReasoning?: string;
  aiRecommendedAction?: string;
}

export interface DockerContainer {
  id: string;
  name: string;
  image: string;
  status: 'running' | 'exited' | 'restarting';
  restarts: number;
  created: string;
  ports: string;
  serverId: string;
  cpu: number;
  ram: number;
}

export interface KubernetesCluster {
  id: string;
  name: string;
  status: 'active' | 'degraded' | 'failed';
  version: string;
  region: string;
}

export interface KubernetesNode {
  name: string;
  status: 'Ready' | 'NotReady';
  cpuAllocatable: string;
  ramAllocatable: string;
  role: string;
}

export interface KubernetesPod {
  name: string;
  namespace: string;
  status: 'Running' | 'Pending' | 'Failed' | 'CrashLoopBackOff';
  restarts: number;
  age: string;
  node: string;
  cpu: string;
  ram: string;
}

export interface KubernetesDeployment {
  name: string;
  namespace: string;
  replicasDesired: number;
  replicasAvailable: number;
  status: 'Available' | 'Progressing' | 'Degraded';
}

export interface KubernetesService {
  name: string;
  namespace: string;
  type: string;
  clusterIp: string;
  externalIp: string;
  ports: string;
}

export interface LogAnalysisResult {
  hasErrors: boolean;
  errorsCount: number;
  warningsCount: number;
  securityRisksCount: number;
  summary: string;
  detectedIssues: Array<{
    severity: 'error' | 'warning' | 'security';
    message: string;
    line: number;
    timestamp?: string;
  }>;
  rootCause: string;
  suggestedFix: string;
  recommendedCommands: string[];
}

export interface AuditLog {
  id: string;
  user: string;
  role: string;
  timestamp: string; // ISO String
  action: string;
  result: string;
  auditEntry: string;
  ip?: string;
  severity?: 'INFO' | 'WARNING' | 'CRITICAL';
  category?: 'AUTH' | 'API' | 'INFRA' | 'DATA' | 'AI' | 'COMPLIANCE';
  integrityHash?: string; // Cryptographic verification hash for compliance
}

export interface ChatMessage {
  id: string;
  sender: 'user' | 'assistant';
  text: string;
  timestamp: string;
  analysis?: LogAnalysisResult; // If the assistant response contains structured log analysis
}
